use crate::host::BrioHostState;
use anyhow::{Context, Result};
use wasmtime::component::Component;
use wasmtime::{Engine, Store};

// Define the world binding for calling the agent
wasmtime::component::bindgen!({
    inline: r#"
        package brio:core;

        interface agent-runner {
            record task-context {
                task-id: string,
                description: string,
                input-files: list<string>,
            }
        
            run: func(context: task-context) -> result<string, string>;
        }

        world smart-agent {
            import agent-runner; // Wait. To CALL it, the Guest EXPORTS it.
            // But from Host perspective, we instantiate a component that exports it.
            export agent-runner; 
        }
    "#,
    world: "smart-agent",
    additional_derives: [serde::Deserialize, serde::Serialize],
});

pub type SmartAgentInstance = SmartAgent;
pub use exports::brio::core::agent_runner::TaskContext;

pub struct AgentRunner {
    engine: Engine,
}

impl AgentRunner {
    pub fn new(engine: Engine) -> Self {
        Self { engine }
    }

    /// Instantiates an agent component and runs it.
    pub async fn run_agent(
        &self,
        component_path: &std::path::Path,
        host_state: BrioHostState,
        context: exports::brio::core::agent_runner::TaskContext,
    ) -> Result<String> {
        let component = Component::from_file(&self.engine, component_path)
            .context("Failed to load component")?;

        let linker = crate::engine::linker::create_linker(&self.engine)?;

        // We need to resolve the `smart-agent` world.
        // The bindings generated by bindgen!["smart-agent"] provide a `SmartAgent::instantiate_async`.

        let mut store = Store::new(&self.engine, host_state);

        let agent = SmartAgent::instantiate_async(&mut store, &component, &linker).await?;

        let result = agent
            .brio_core_agent_runner()
            .call_run(&mut store, &context)?;

        result.map_err(|e| anyhow::anyhow!("Agent execution failed: {}", e))
    }
}
