//! gRPC protocol definitions for mesh transport.
//!
//! This module contains the generated protobuf code for inter-node communication
//! in the Brio service mesh, including message routing and health checks.

// Note: This file is auto-generated by tonic from protobuf definitions.
// The following allows are for generated code quality.
#![allow(missing_docs)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::default_trait_access)]
#![allow(clippy::too_many_lines)]
tonic::include_proto!("mesh");
